# Site settings
title: The Cat's Eye Student Pub and Lounge
email: manager@catseye.ca
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thecatseye.ca" # the base hostname & protocol for your site
twitter_username: viccatseye
github_username:  ryanfan

# Build settings
markdown: kramdown
highlighter: pygments

navigation:
 - title: Events
   url: /events/
 - title: Media
   url: /media/
 - title: Staff
   url: /staff/
 - title: Contact
   url: /contact/


