# Site settings
title: The Cat's Eye
title_suffix: Student Pub & Lounge
email: manager@thecatseye.ca
description: > # this means to ignore newlines until "baseurl:"
  The Cat's Eye is Victoria College's student-run lounge and pub. Come
  hang out with friends, study, or play games. The space is also available
  for booking for Victoria College groups.
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://thecatseye.ca   # with the https protocol
enforce_ssl: thecatseye.ca   # without any protocol
twitter_username: viccatseye
github_username:  thecatseye

# Build settings
markdown: kramdown
highlighter: pygments

navigation:
 - title: Booking
   url: /booking/
 - title: Events
   url: /events/
 - title: Media
   url: /media/
 - title: Staff
   url: /staff/
 - title: Contact
   url: /contact/

maintenance: 1
