# Site settings
title: The Cat's Eye
title_suffix: Student Pub & Lounge
email: manager@catseye.ca
description: > # this means to ignore newlines until "baseurl:"
  The Cat's Eye is Victoria College's student-run lounge and pub. Come
  hang out with friends, study, or play games. The space is also available
  for booking for Victoria College groups.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thecatseye.ca" # the base hostname & protocol for your site
twitter_username: viccatseye
github_username:  thecatseye

# Build settings
markdown: kramdown
highlighter: pygments

navigation:
 - title: About
   url: /about/
 - title: Events
   url: /events/
 - title: Media
   url: /media/
 - title: Staff
   url: /staff/
 - title: Contact
   url: /contact/
